{
 "title": "VMware vSphere - Overview (Prometheus)",
 "description": "VMware vSphere Dashboard (Grafana 11.x / InfluxDB v2.x)",
 "tags": [
  "VMware",
  "vSphere Overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "vcenter", "label": "vCenter Server", "query": "vcsim" },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_host_power_state, cluster_name)"
    }
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": {
     "query": "label_values(vmware_host_power_state, host_name)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values(vmware_datastore_capacity_size, ds_name)"
    }
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": {
     "query": "label_values(vmware_vm_power_state, vm_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Datacenter Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vSphere Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (dc_name) (vmware_host_power_state))",
     "legendFormat": "vCenter Summary"
    },
    {
     "expr": "count(count by (cluster_name) (vmware_host_power_state{cluster_name!=\"\"}))",
     "legendFormat": "Cluster Summary"
    },
    {
     "expr": "count(count by (host_name) (vmware_host_power_state))",
     "legendFormat": "ESXi Summary"
    },
    { "expr": "count(vmware_vm_power_state)", "legendFormat": "VM Summary" },
    {
     "expr": "count(vmware_datastore_capacity_size)",
     "legendFormat": "Datastore Summary"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$clustername Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "repeat": "clustername",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - avg by (cluster_name) (vmware_host_boot_timestamp_seconds{cluster_name=~\"$clustername\"})) * 1000",
     "legendFormat": "{{cluster_name}}"
    },
    {
     "expr": "avg by (cluster_name) ((vmware_host_cpu_usage{cluster_name=~\"$clustername\"} / vmware_host_cpu_max) * 100)",
     "legendFormat": "{{cluster_name}}"
    },
    {
     "expr": "avg by (cluster_name) ((vmware_host_memory_usage{cluster_name=~\"$clustername\"} / vmware_host_memory_max) * 100)",
     "legendFormat": "{{cluster_name}}"
    },
    {
     "expr": "avg by (cluster_name) ((vmware_datastore_capacity_size - vmware_datastore_freespace_size) / vmware_datastore_capacity_size * 100)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Overprovisioned", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$esxi Overprovisioned - CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "repeat": "esxi",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_name) (vmware_host_num_cpu{host_name=~\"$esxi\"})",
     "legendFormat": "{{host_name}}"
    },
    {
     "expr": "sum by (host_name) (vmware_vm_num_cpu{host_name=~\"$esxi\"})",
     "legendFormat": "{{host_name}}"
    },
    {
     "expr": "sum by (host_name) (vmware_vm_num_cpu{host_name=~\"$esxi\"}) / sum by (host_name) (vmware_host_num_cpu{host_name=~\"$esxi\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "$esxi Overprovisioned - RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "esxi",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_name) (vmware_host_memory_max{host_name=~\"$esxi\"}) / 1024",
     "legendFormat": "{{host_name}}"
    },
    {
     "expr": "sum by (host_name) (vmware_vm_memory_max{host_name=~\"$esxi\"})",
     "legendFormat": "{{host_name}}"
    },
    {
     "expr": "sum by (host_name) (vmware_vm_memory_max{host_name=~\"$esxi\"}) / (sum by (host_name) (vmware_host_memory_max{host_name=~\"$esxi\"}))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Cluster CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{cluster_name=~\"$clustername\"} / vmware_host_cpu_max{cluster_name=~\"$clustername\"}) * 100",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{cluster_name=~\"$clustername\"} / vmware_host_memory_max{cluster_name=~\"$clustername\"}) * 100",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_datastore_capacity_size{ds_name=~\"$datastore\"} - vmware_datastore_freespace_size{ds_name=~\"$datastore\"}) / vmware_datastore_capacity_size{ds_name=~\"$datastore\"} * 100",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_host_net_bytesRx_average{cluster_name=~\"$clustername\"}",
     "legendFormat": "{{cluster_name}} - Received"
    },
    {
     "expr": "vmware_host_net_bytesTx_average{cluster_name=~\"$clustername\"}",
     "legendFormat": "{{cluster_name}} - Transmited"
    }
   ]
  },
  {
   "title": "Cluster Storage Adapter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (host_name) (vmware_host_disk_read_average{cluster_name=~\"$clustername\"})",
     "legendFormat": "{{host_name}} read"
    },
    {
     "expr": "sum by (host_name) (vmware_host_disk_write_average{cluster_name=~\"$clustername\"})",
     "legendFormat": "{{host_name}} write"
    }
   ]
  },
  { "title": "Datastore Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$datastore",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "repeat": "datastore",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_datastore_capacity_size{ds_name=~\"$datastore\"} - vmware_datastore_freespace_size{ds_name=~\"$datastore\"}) / vmware_datastore_capacity_size{ds_name=~\"$datastore\"} * 100",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  { "title": "Hypervisor Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Hypervisor CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxi\"} / vmware_host_cpu_max{host_name=~\"$esxi\"}) * 100",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Hypervisor Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxi\"} / vmware_host_memory_max{host_name=~\"$esxi\"}) * 100",
     "legendFormat": "{{host_name}} mem usage average"
    }
   ]
  },
  {
   "title": "Hypervisor Net Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_host_net_usage_average{host_name=~\"$esxi\"}",
     "legendFormat": "{{host_name}} net usage average"
    }
   ]
  },
  {
   "title": "vCenter CPU/RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "vmware_vm_cpu_usage_average{}", "legendFormat": "vcsim CPU" },
    { "expr": "vmware_vm_mem_usage_average{}", "legendFormat": "vcsim RAM" }
   ]
  },
  { "title": "Virtual Machine Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Virtual Machine CPU Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usage_average{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Memory Usage Avg.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Virtual Machine CPU READY ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Network Usage Avg (Kbps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_vm_net_usage_average{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Read VMFS Block IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Write VMFS Block IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vmware_vm_disk_write_average{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Block Latency Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vmware_vm_disk_maxTotalLatency_latest{vm_name=~\"$virtualmachine\"}",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_maxTotalLatency_latest{}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 65 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>"
   }
  }
 ]
}