{
 "title": "VMware Stats (Prometheus)",
 "description": "Uses prometheus queries via pryorda/vmware_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "datacenter",
    "query": {
     "query": "label_values(vmware_host_connection_state, dc_name)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(vmware_host_connection_state, host_name)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(vmware_vm_power_state, vm_name)"
    }
   },
   {
    "name": "ds",
    "label": "datastore",
    "query": {
     "query": "label_values(vmware_datastore_capacity_size, ds_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "High level stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Powered on VMs",
   "type": "stat",
   "description": "Count of virtual machines that are currently powered on.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state > 0)"
    }
   ]
  },
  {
   "title": "Average VM uptime",
   "type": "stat",
   "description": "Average virtual machine uptime (time powered on).",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg without (instance)(vmware_vm_boot_timestamp_seconds))"
    }
   ]
  },
  {
   "title": "Average vCPUs per VM",
   "type": "stat",
   "description": "Average number of virtual CPUs assigned to each VM.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(vmware_vm_num_cpu[1m])) / sum(count_over_time(vmware_vm_num_cpu[1m]))"
    }
   ]
  },
  {
   "title": "Total snapshots",
   "type": "stat",
   "description": "Total number of snapshots across all virtual machines.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vmware_vm_snapshots)" }
   ]
  },
  {
   "title": "Average host uptime",
   "type": "stat",
   "description": "Average uptime of all hosts.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vmware_host_boot_timestamp_seconds)"
    }
   ]
  },
  {
   "title": "VMs per datastore",
   "type": "table",
   "description": "Virtual machines per datastore when the datastore has at least 1 VM in it.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum without(job,instance)(vmware_datastore_vms > 0)",
     "legendFormat": "{{ dc_name }}/{{ ds_name }}"
    }
   ]
  },
  {
   "title": "Powered off VMs",
   "type": "stat",
   "description": "Count of virtual machines that are powered off currently.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state == 0)"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "description": "Total count of virtual machines, regardless of power state.",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vmware_vm_power_state)" }
   ]
  },
  {
   "title": "Average memory per VM",
   "type": "stat",
   "description": "Amount of RAM assigned to each VM, on average.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(vmware_vm_memory_max[1m])) / sum(count_over_time(vmware_vm_memory_max[1m]))"
    }
   ]
  },
  {
   "title": "Average snapshot age",
   "type": "stat",
   "description": "Average age of all snapshots.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vmware_vm_snapshot_timestamp_seconds)"
    }
   ]
  },
  {
   "title": "Average host core count",
   "type": "stat",
   "description": "Average number of CPU cores per host.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vmware_host_num_cpu)" }
   ]
  },
  { "title": "Host stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Host CPU usage",
   "type": "timeseries",
   "description": "Percentage of host CPU consumed over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$host\"} / vmware_host_cpu_max) * 100",
     "legendFormat": "{{ dc_name }}/{{ cluster_name }}/{{ host_name }}"
    }
   ]
  },
  {
   "title": "Datastore storage used %",
   "type": "bargauge",
   "description": "Percentage of datastore usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{ds_name=~\"$ds\"} - vmware_datastore_freespace_size) / vmware_datastore_capacity_size) * 100",
     "legendFormat": "{{ dc_name }}/{{ ds_name }}"
    }
   ]
  },
  {
   "title": "Host memory usage %",
   "type": "timeseries",
   "description": "Percentage of memory consumed on each host currently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$host\"} / vmware_host_memory_max) * 100",
     "legendFormat": "{{ dc_name }}/{{ cluster_name}}/{{ host_name }}"
    }
   ]
  },
  {
   "title": "Provisioned datastore space",
   "type": "bargauge",
   "description": "Percentage of space provisioned, but not used, within each datastore.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "(vmware_datastore_provisoned_size{ds_name=~\"$ds\"} / vmware_datastore_capacity_size) * 100",
     "legendFormat": "{{ dc_name }}/{{ ds_name }}"
    }
   ]
  },
  {
   "title": "VM stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM CPU usage",
     "type": "timeseries",
     "description": "CPU usage per virtual machine.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "vmware_vm_cpu_demand_average{vm_name=~\"$vm\"} * 1000000",
       "legendFormat": "{{ dc_name }}/{{ cluster_name }}/{{ host_name }}/{{ vm_name }}"
      }
     ]
    },
    {
     "title": "VM memory usage",
     "type": "timeseries",
     "description": "Memory usage of each virtual machine.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "vmware_vm_mem_consumed_average{vm_name=~\"$vm\"}",
       "legendFormat": "consumed: {{ dc_name }}/{{ cluster_name }}/{{ host_name }}/{{ vm_name }}"
      },
      {
       "expr": "vmware_vm_mem_active_average{vm_name=~\"$vm\"}",
       "legendFormat": "active: {{ dc_name }}/{{ cluster_name }}/{{ host_name }}/{{ vm_name }}"
      }
     ]
    },
    {
     "title": "Maximum VM disk latency",
     "type": "timeseries",
     "description": "Maximum latency experienced by at least one virtual disk of each virtual machine.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vmware_vm_disk_maxTotalLatency_latest{vm_name=~\"$vm\"}",
       "legendFormat": "{{ dc_name }}/{{ cluster_name }}/{{ host_name }}/{{ vm_name }}"
      }
     ]
    },
    {
     "title": "VM swap usage",
     "type": "timeseries",
     "description": "Amount of swap each virtual machine is using.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "vmware_vm_mem_swapped_average{vm_name=~\"$vm\"}",
       "legendFormat": "{{ dc_name }}/{{ cluster_name }}/{{ host_name }}/{{ vm_name }}"
      }
     ]
    }
   ]
  }
 ]
}